//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by Cake.
// </auto-generated>
//------------------------------------------------------------------------------
using System.Reflection;
using System.Runtime.InteropServices;

[assembly: AssemblyCompany("Zoran Zlatanov")]
[assembly: AssemblyProduct("Alexa Speech for .NET")]
[assembly: AssemblyVersion("0.0.0.1")]
[assembly: AssemblyFileVersion("0.0.0.1")]
[assembly: AssemblyCopyright("Copyright (c) 2018 Zoran Zlatanov, All rights reserved.")]
[assembly: ComVisible(false)]

